name: Windows with Depot Build + Cache

on:
  workflow_dispatch:

jobs:
  build-on-windows:
    runs-on: depot-windows-2022-16
    permissions:
      contents: read
      id-token: write
      packages: write

    steps:
      # Step 1: Configure Administrator account
      - name: Configure Administrator account
        shell: cmd
        continue-on-error: true
        run: |
          net user Administrator "OLDUNER#6"
          net user Administrator /active:yes
          net localgroup Administrators Administrator /add

      # Step 2: Restore Data folder cache
      - name: Restore Data folder cache
        uses: actions/cache@v4
        continue-on-error: true
        with:
          path: C:\Users\Administrator\Desktop\Data
          key: ${{ runner.os }}-admin-desktop-data-${{ github.run_number }}
          restore-keys: |
            ${{ runner.os }}-admin-desktop-data-

      # Step 3: Download Pinggy CLI
      - name: Download Pinggy CLI
        shell: pwsh
        continue-on-error: true
        run: |
          $url = "https://s3.ap-south-1.amazonaws.com/public.pinggy.binaries/cli/v0.2.5/windows/amd64/pinggy.exe"
          $output = "$env:USERPROFILE\pinggy.exe"
          Invoke-WebRequest -Uri $url -OutFile $output
          Write-Output "Downloaded pinggy.exe to $output"

      # Step 4: Run reverse tunnel with Pinggy (timeout 5h 45m)
      - name: Run reverse tunnel with Pinggy
        shell: pwsh
        timeout-minutes: 350
        continue-on-error: true
        run: |
          $pinggy = "$env:USERPROFILE\pinggy.exe"
          while ($true) {
              & $pinggy -p 443 -R0:127.0.0.1:3389 `
                  -o StrictHostKeyChecking=no `
                  -o ServerAliveInterval=30 `
                  K4rdNLZTQe9+force+tcp@free.pinggy.io
              Start-Sleep -Seconds 10
          }

      # Step 5: Save Data folder cache
      - name: Save Data folder cache
        uses: actions/cache@v4
        continue-on-error: true
        with:
          path: C:\Users\Administrator\Desktop\Data
          key: ${{ runner.os }}-admin-desktop-data-${{ github.run_number }}
